# Generated by Django 2.0.5 on 2018-06-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='noname', max_length=50)),
                ('in_salon', models.BooleanField(default=False)),
            ],
        ),
    ]
