# Generated by Django 2.0.6 on 2018-06-08 04:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='noname', max_length=50)),
                ('rotation', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(default='SRID=3857;POINT(0.0 0.0)', srid=4326)),
            ],
        ),
    ]
